### ISSUE TITLE
Issue loading numeric types in Python using fast parquet

### ISSUE THREAD

**Issue by sk2** [domoritz/csv2parquet#90]
Hi, I'm trying something that should be relatively common, but it's not loading into pandas using fast parquet, and I'm hoping for some pointers to debug.

I've reduced it down to an issue writing numeric values:
```import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randint(0,10,size=(10, 4)))
df.to_csv("test.csv", header=False)
```

gives
```
0,3,4,5,1
1,6,0,7,2
2,8,6,9,3
3,6,6,2,4
4,7,5,9,0
5,4,1,2,0
6,6,3,8,7
7,9,2,4,0
8,6,4,1,6
9,4,9,5,7
```

```
./csv2parquet test.csv test.parquet --header false
```
goes ok, but I cannot read it in Python:

```
python -c "import pandas as pd; pd.read_parquet('test.parquet')"
```

gives
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "python3.10/site-packages/pandas/io/parquet.py", line 493, in read_parquet
    return impl.read(
  File "python3.10/site-packages/pandas/io/parquet.py", line 345, in read
    parquet_file = self.api.ParquetFile(path, **parquet_kwargs)
  File "python3.10/site-packages/fastparquet/api.py", line 130, in __init__
    self._parse_header(fn, verify)
  File "python3.10/site-packages/fastparquet/api.py", line 225, in _parse_header
    self._set_attrs()
  File "python3.10/site-packages/fastparquet/api.py", line 239, in _set_attrs
    self._dtypes()
  File "python3.10/site-packages/fastparquet/api.py", line 927, in _dtypes
    if st[3]:
KeyError: 3
```

I've tried all sorts of combinations with headers, etc, but same issue.

Numeric data into Python should be relatively common so I'm happy to try and help figure out what's going on as other users will benefit from it too.

**Comment by domoritz** [comment]
Thanks for the issue. Can you run the tool with dry run and print the schema? I wonder whether the inference is maybe botched.

**Comment by sk2** [comment]
Yeah, it's a bit perplexing. I was narrowing it down from larger sets to this tiny generated one, and the schema for them all looked ok (to a novice).
For this it's:
```
 ./csv2parquet test.csv test.parquet --header false -n
Schema:
{
  "fields": [
    {
      "name": "column_1",
      "nullable": false,
      "type": {
        "name": "int",
        "bitWidth": 64,
        "isSigned": true
      },
      "children": []
    },
    {
      "name": "column_2",
      "nullable": false,
      "type": {
        "name": "int",
        "bitWidth": 64,
        "isSigned": true
      },
      "children": []
    },
    {
      "name": "column_3",
      "nullable": false,
      "type": {
        "name": "int",
        "bitWidth": 64,
        "isSigned": true
      },
      "children": []
    },
    {
      "name": "column_4",
      "nullable": false,
      "type": {
        "name": "int",
        "bitWidth": 64,
        "isSigned": true
      },
      "children": []
    },
    {
      "name": "column_5",
      "nullable": false,
      "type": {
        "name": "int",
        "bitWidth": 64,
        "isSigned": true
      },
      "children": []
    }
  ],
  "metadata": {}
}
```

And this is the same if I did have a dummy header row, and various other combinations.

**Comment by domoritz** [comment]
Yeah. If you can make a small example, I think it would be good to file this with the arrow folks.

**Comment by sk2** [comment]
Will do - what would constitute the example?

**Comment by domoritz** [comment]
Actually, looking at https://pandas.pydata.org/docs/reference/api/pandas.read_parquet.html, there are different parsers. Can you try pyarrow? If it works with that library, it's a bug in fastparquet, and not the rust code.

**Comment by domoritz** [comment]
Yep, so 

```
python -c "import pandas as pd; pd.read_parquet('test.parquet', engine='pyarrow')"
```

works

```
python -c "import pandas as pd; pd.read_parquet('test.parquet', engine='fastparquet')"
```

shows the same error. So I think this could be an issue with fastparquet.

**Comment by sk2** [comment]
Will do - have reported it to them at https://github.com/dask/fastparquet/issues/792

thanks
